/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package controller

import (
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"strings"

	databasev1alpha1 "github.com/paradedb/paradedb-operator/api/v1alpha1"
)

// generateRandomPassword generates a random password of the specified length
func generateRandomPassword(length int) string {
	bytes := make([]byte, length)
	if _, err := rand.Read(bytes); err != nil {
		// Fallback to a default password if random generation fails
		return "paradedb-default-password"
	}
	// Use URL-safe base64 encoding and trim to desired length
	password := base64.URLEncoding.EncodeToString(bytes)
	if len(password) > length {
		password = password[:length]
	}
	return password
}

// buildPostgresConfig generates the PostgreSQL configuration
func buildPostgresConfig(paradedb *databasev1alpha1.ParadeDB) string {
	var config strings.Builder

	// Default configuration
	config.WriteString("# ParadeDB PostgreSQL Configuration\n")
	config.WriteString("# Generated by paradedb-operator\n\n")

	// Listen settings
	config.WriteString("listen_addresses = '*'\n")
	config.WriteString("port = 5432\n\n")

	// Connection settings
	config.WriteString("max_connections = 100\n")
	config.WriteString("superuser_reserved_connections = 3\n\n")

	// Memory settings
	config.WriteString("shared_buffers = 128MB\n")
	config.WriteString("effective_cache_size = 512MB\n")
	config.WriteString("maintenance_work_mem = 64MB\n")
	config.WriteString("work_mem = 4MB\n\n")

	// WAL settings
	config.WriteString("wal_level = replica\n")
	config.WriteString("max_wal_senders = 10\n")
	config.WriteString("max_replication_slots = 10\n")
	config.WriteString("wal_keep_size = 1GB\n\n")

	// Logging
	config.WriteString("logging_collector = on\n")
	config.WriteString("log_directory = 'log'\n")
	config.WriteString("log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'\n")
	config.WriteString("log_rotation_age = 1d\n")
	config.WriteString("log_rotation_size = 100MB\n")
	config.WriteString("log_min_messages = warning\n")
	config.WriteString("log_min_error_statement = error\n\n")

	// Checkpoint settings
	config.WriteString("checkpoint_timeout = 5min\n")
	config.WriteString("checkpoint_completion_target = 0.9\n\n")

	// Shared preload libraries for ParadeDB extensions
	config.WriteString("# ParadeDB Extensions\n")
	var preloadLibs []string

	if paradedb.Spec.Extensions.PgSearch {
		preloadLibs = append(preloadLibs, "pg_search")
	}
	if paradedb.Spec.Extensions.PgAnalytics {
		preloadLibs = append(preloadLibs, "pg_analytics")
	}
	if paradedb.Spec.Extensions.PgVector {
		preloadLibs = append(preloadLibs, "vector")
	}

	if len(preloadLibs) > 0 {
		config.WriteString(fmt.Sprintf("shared_preload_libraries = '%s'\n\n", strings.Join(preloadLibs, ",")))
	}

	// TLS configuration if enabled
	if paradedb.IsTLSEnabled() {
		config.WriteString("# TLS Configuration\n")
		config.WriteString("ssl = on\n")
		config.WriteString("ssl_cert_file = '/etc/postgresql/tls/tls.crt'\n")
		config.WriteString("ssl_key_file = '/etc/postgresql/tls/tls.key'\n")
		config.WriteString("ssl_ca_file = '/etc/postgresql/tls/ca.crt'\n\n")
	}

	// Apply custom PostgreSQL configuration
	if len(paradedb.Spec.PostgresConfig) > 0 {
		config.WriteString("# Custom Configuration\n")
		for key, value := range paradedb.Spec.PostgresConfig {
			config.WriteString(fmt.Sprintf("%s = %s\n", key, value))
		}
	}

	return config.String()
}

// buildPgHBAConfig generates the pg_hba.conf configuration
func buildPgHBAConfig(paradedb *databasev1alpha1.ParadeDB) string {
	var config strings.Builder

	config.WriteString("# ParadeDB pg_hba.conf\n")
	config.WriteString("# Generated by paradedb-operator\n\n")

	// Default rules
	config.WriteString("# TYPE  DATABASE        USER            ADDRESS                 METHOD\n\n")

	// Local connections
	config.WriteString("# Local connections\n")
	config.WriteString("local   all             all                                     trust\n")
	config.WriteString("host    all             all             127.0.0.1/32            scram-sha-256\n")
	config.WriteString("host    all             all             ::1/128                 scram-sha-256\n\n")

	// Replication
	config.WriteString("# Replication connections\n")
	config.WriteString("local   replication     all                                     trust\n")
	config.WriteString("host    replication     all             127.0.0.1/32            scram-sha-256\n")
	config.WriteString("host    replication     all             ::1/128                 scram-sha-256\n\n")

	// Remote connections
	config.WriteString("# Remote connections\n")
	if paradedb.IsTLSEnabled() {
		config.WriteString("hostssl all             all             0.0.0.0/0               scram-sha-256\n")
		config.WriteString("hostssl all             all             ::/0                    scram-sha-256\n")
	} else {
		config.WriteString("host    all             all             0.0.0.0/0               scram-sha-256\n")
		config.WriteString("host    all             all             ::/0                    scram-sha-256\n")
	}

	// Custom pg_hba entries
	if len(paradedb.Spec.Auth.PgHBA) > 0 {
		config.WriteString("\n# Custom rules\n")
		for _, rule := range paradedb.Spec.Auth.PgHBA {
			config.WriteString(rule + "\n")
		}
	}

	return config.String()
}

// buildInitScript generates the initialization SQL script
func buildInitScript(paradedb *databasev1alpha1.ParadeDB) string {
	var script strings.Builder

	script.WriteString("-- ParadeDB Initialization Script\n")
	script.WriteString("-- Generated by paradedb-operator\n\n")

	// Create extensions
	script.WriteString("-- Enable ParadeDB Extensions\n")

	if paradedb.Spec.Extensions.PgSearch {
		script.WriteString("CREATE EXTENSION IF NOT EXISTS pg_search;\n")
	}

	if paradedb.Spec.Extensions.PgAnalytics {
		script.WriteString("CREATE EXTENSION IF NOT EXISTS pg_analytics;\n")
	}

	if paradedb.Spec.Extensions.PgVector {
		script.WriteString("CREATE EXTENSION IF NOT EXISTS vector;\n")
	}

	// Additional extensions
	for _, ext := range paradedb.Spec.Extensions.Additional {
		script.WriteString(fmt.Sprintf("CREATE EXTENSION IF NOT EXISTS %s;\n", ext))
	}

	script.WriteString("\n")

	// Create additional users if specified
	if len(paradedb.Spec.Auth.Users) > 0 {
		script.WriteString("-- Create additional users\n")
		for _, user := range paradedb.Spec.Auth.Users {
			// Note: Password will be set via environment variable or secret mount
			script.WriteString(fmt.Sprintf("DO $$\nBEGIN\n  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '%s') THEN\n    CREATE ROLE %s WITH LOGIN;\n  END IF;\nEND\n$$;\n\n", user.Name, user.Name))

			// Grant database access
			for _, db := range user.Databases {
				script.WriteString(fmt.Sprintf("GRANT CONNECT ON DATABASE %s TO %s;\n", db, user.Name))
			}

			// Grant privileges
			for _, priv := range user.Privileges {
				script.WriteString(fmt.Sprintf("-- Grant %s to %s\n", priv, user.Name))
			}
		}
	}

	script.WriteString("\n-- Initialization complete\n")

	return script.String()
}
